export const FETCH_MENU_REQUESTED = 'FETCH_MENU_REQUESTED';
export const FETCH_MENU_SUCCEEDED = 'FETCH_MENU_SUCCEEDED';
export const FETCH_MENU_FAILED = 'FETCH_MENU_FAILED';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';

export const FINISH_PURCHASE = 'FINISH_PURCHASE';
